  version: '3'
  services:
    homeassistant:
      container_name: home-assistant
      image: homeassistant/home-assistant
      volumes:
        - /Users/mdlima/Projects/home-assistant/config:/config
        - /etc/localtime:/etc/localtime:ro
      restart: always
      ports:
        - "8123:8123"
      # network_mode: host
      environment:
        - "TZ=America/Sao_Paulo"